# Generated by Django 5.1 on 2024-08-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Birthday', models.DateTimeField()),
                ('Cpf', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('Height', models.DecimalField(decimal_places=3, max_digits=3, max_length=5)),
                ('Weight', models.DecimalField(decimal_places=3, max_digits=3, max_length=5)),
            ],
        ),
    ]
