# Generated by Django 5.1 on 2024-08-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_height_alter_person_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Height',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='Weight',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=10),
        ),
    ]
